apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: tempo

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          name: traceId
          url: '$${__value.raw}'
          urlDisplayLabel: View Trace

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 3.2.1
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
