services:
  app:
    build:
      # use local image
      dockerfile: Dockerfile
      context: .
    container_name: emmett_api
    profiles: [app]
    environment:
      - POSTGRESQL_CONNECTION_STRING=postgresql://postgres@postgres:5432/postgres
    networks:
      - postgresql_network
    ports:
      - '3000:3000'

  #######################################################
  #  PostgreSQL
  #######################################################
  postgres:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - postgresql_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - ./docker/pgAdmin/pgpass:/pgpass
      - ./docker/pgAdmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgresql_network

networks:
  postgresql_network:
    driver: bridge

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
