/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/emmett-sqlite/wrangler.durable-object.jsonc --include-runtime=false packages/emmett-sqlite/worker-configuration.d.ts` (hash: 655409be9515ec79758409916af1b20a)
interface __BaseEnv_Env {
	TEST_OBJECT: DurableObjectNamespace<import("./src/storage/durableObject/testing/durableObjectTestWorker").EmmettDurableObjectSQLiteTestObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/storage/durableObject/testing/durableObjectTestWorker");
		durableNamespaces: "EmmettDurableObjectSQLiteTestObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
